[package]
name = "glass-pgp"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
pgp = { version = "0.19", default-features = false, features = ["wasm"] }
rand = { version = "0.8", features = ["getrandom"] }
getrandom = { version = "0.2", features = ["js"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "wasmbind"] }
hex = "0.4"
smallvec = "1"

[profile.release]
opt-level = "z"
lto = true
strip = true
codegen-units = 1

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
