#!/usr/bin/env python3
# Generates sitemap/index.html and /sitemap.xml from the data model below.
# Edit the model, run `python3 sitemap/build.py` from the repo root, commit both outputs.

import html
import re

# ── data model ──────────────────────────────────────────────────────────────

CARDS = [
    ('/',            'landing',   False),
    ('/sitemap/',    'this map',  False),
    ('/ittybitty/',  'url = doc', False),
    ('/qii/',        'quake ii',  False),
    ('/shrtlnk/',    'shortener', True),    # True: page fetches the worker
    ('/tools/',      '7 utils',   True),
]

WORKER_GROUPS = [
    ('reflect', '/s/ip · /s/headers'),
    ('lookup',  '/s/dns · /s/ping · /s/whois'),
    ('store',   '/s/go · /s/tmp'),
]

ROUTES = [
    ('GET',  '/s/ip',       'your ip, echoed back',  ''),
    ('GET',  '/s/headers',  'your request headers',  ''),
    ('GET',  '/s/dns/…',    'doh lookup',            'ext'),
    ('GET',  '/s/ping/…',   'timed fetch',           'ext'),
    ('GET',  '/s/whois/…',  'rdap lookup',           'ext'),
    ('POST', '/s/go',       'mint short link',       'r2'),
    ('GET',  '/s/go/:id',   'resolve link',          'r2'),
    ('POST', '/s/tmp',      'file drop, 1 hr',       'r2'),
    ('GET',  '/s/tmp/:id',  'fetch dropped file',    'r2'),
]

R2_BOX = ('r2 · sea-glass-store', [
    'short:* → target urls',
    'tmp:*   → files, 1 hr',
])

EXT_BOX = ('external services', [
    'cloudflare-dns.com',
    'rdap.org / verisign',
    'any pinged target',
])

FLOWS = [
    ('mint',    '/shrtlnk/ ── POST /s/go ──▶ crystal ── put short:id ──▶ r2'),
    ('reply',   'crystal ──▶ { id, https://seaof.glass/s/go/id }'),
    ('resolve', 'visitor ── GET /s/go/id ──▶ crystal ── get short:id ──▶ r2'),
    ('land',    'crystal ── 302 ──▶ /shrtlnk/r/?to=target ── click-through ──▶ target'),
]

CLIENT_ONLY = [
    ('/ittybitty/', 'the document lives in the url fragment'),
    ('/qii/',       'game data cached in indexeddb'),
    ('/tools/pgp',  'keys and plaintext never leave the tab'),
]

TITLES = [
    'your browser',
    'seaof.glass',
    'cloudflare dns zone',
    'github pages · static site',
    'crystal · cloudflare worker',
    'r2 · sea-glass-store',
    'external services',
    'the short-link round trip',
    'client-side only · never talk to crystal',
    '/sitemap/', '/ittybitty/', '/qii/', '/shrtlnk/', '/tools/',
]

ROLES = [
    ('/', 'landing',
     'the front door. one hand-written page, inline css, zero javascript. '
     'links to everything below and nothing else.'),
    ('/sitemap/', 'this page',
     'the map you are reading, generated by <code>sitemap/build.py</code>: '
     'edit the data model, run it, commit the output. the diagram geometry is '
     'computed, never hand-aligned.'),
    ('/ittybitty/', 'the url is the document',
     'an editor whose files live entirely in the link: content is lzma-compressed '
     '(and optionally encrypted) into the url fragment, so sharing the link '
     '<em>is</em> publishing. codemirror for editing, marked for markdown preview, '
     'qr export for handing a whole document to a phone, and a service worker that '
     'makes it installable and offline-capable. no server ever sees a byte of the '
     'document, because the fragment never leaves the browser.'),
    ('/qii/', 'quake ii',
     'the qwasm2 engine compiled to webassembly, with gl1, gles3, and software '
     'renderers. jszip unpacks game data in the browser and indexeddb '
     '(<code>qii-assets</code>) caches the pak files, so the download happens once. '
     'after the first load it is a local game that happens to live at a url.'),
    ('/shrtlnk/', 'url shortener',
     'the ui posts a url to <code>/s/go</code> and gets back '
     '<code>seaof.glass/s/go/:id</code>. resolving a short link never jumps straight '
     'to the target: crystal 302s to the <code>/shrtlnk/r/</code> splash, which '
     'previews the destination behind a disclaimer and a deliberate click-through. '
     'no blind redirects.'),
    ('/tools/', 'seven single-file utilities',
     '<code>ip</code>, <code>headers</code>, <code>dns</code>, <code>ping</code>, and '
     '<code>whois</code> are thin fronts for the matching <code>/s/*</code> route: '
     'the worker either reflects what it sees (your ip, your headers) or asks the '
     'outside world on your behalf (doh, rdap, a timed fetch). <code>tmp</code> '
     'drops a file into r2 with a one-hour expiry. <code>pgp</code> is the odd one '
     'out: it needs no server at all.'),
    ('/tools/pgp/', 'openpgp runtime',
     'rust (the rPGP crate) compiled to wasm, executed inside a web worker so '
     'rsa-4096 keygen does not freeze the tab. keygen, encrypt, and decrypt all run '
     'locally; keys and plaintext never leave the page. the rust source ships '
     'alongside the built wasm, so the artifact is reproducible.'),
    ('crystal', 'cloudflare worker',
     'the only server code on the site: one typescript file behind '
     '<code>seaof.glass/s/*</code>. nine routes in three families (reflect, lookup, '
     'store), rate-limited to 60 requests a minute per ip, cors locked to the site '
     'origin. it holds no logic beyond what the static pages cannot do themselves: '
     'reflecting network facts, fetching cross-origin, and touching storage.'),
    ('r2', 'sea-glass-store',
     'the only state anywhere. <code>short:*</code> keys map ids to target urls and '
     'live forever; <code>tmp:*</code> keys hold uploads stamped with an expiry that '
     'is checked, and purged, on read. everything else on the site is stateless or '
     'client-side.'),
    ('the repo', 'Lasimeri/lasimeri.github.io',
     'both halves live in one repository. a push to <code>main</code> republishes '
     'the static site through github pages; <code>wrangler deploy</code> in '
     '<code>worker/</code> republishes crystal. the two deploys are independent and '
     'meet only at the <code>/s/*</code> fetch boundary.'),
]

SITEMAP_XML_PATHS = [
    '/', '/sitemap/', '/ittybitty/', '/qii/', '/shrtlnk/',
    '/tools/ip.html', '/tools/headers.html', '/tools/dns.html',
    '/tools/ping.html', '/tools/whois.html', '/tools/tmp.html',
    '/tools/pgp.html',
]
LASTMOD = '2026-08-13'

# ── canvas + box primitives ─────────────────────────────────────────────────

PAD = 3


class Canvas:
    def __init__(self, width):
        self.width = width
        self.rows = []

    def _ensure(self, r):
        while len(self.rows) <= r:
            self.rows.append([' '] * self.width)

    def put(self, r, c, s):
        self._ensure(r)
        assert c + len(s) <= self.width, f'row {r} overflows: {s!r}'
        for i, ch in enumerate(s):
            self.rows[r][c + i] = ch

    def putv(self, r1, r2, c, ch='│'):
        for r in range(r1, r2 + 1):
            self.put(r, c, ch)

    def hline(self, r, c1, c2, ch='─'):
        self.put(r, c1, ch * (c2 - c1 + 1))

    def text(self):
        return '\n'.join(''.join(r).rstrip() for r in self.rows)


def box_lines(titles, body, single=True, inner=None, pad=PAD):
    """Box as a list of lines; odd outer width so an exact center column exists."""
    tl, tr, bl, br, hz, vt = ('┌', '┐', '└', '┘', '─', '│') if single else \
                             ('╔', '╗', '╚', '╝', '═', '║')
    content = list(titles) + ([''] if body else []) + list(body)
    w = max(max(len(l) for l in content) + 2 * pad, inner or 0)
    if (w + 2) % 2 == 0:
        w += 1
    out = [tl + hz * w + tr]
    for i, l in enumerate(content):
        out.append(vt + (l.center(w) if i < len(titles) else (' ' * pad + l).ljust(w)) + vt)
    out.append(bl + hz * w + br)
    return out


def paint(canvas, r, center, lines):
    """Paint box lines centered on a column; return (top, bottom, left, right)."""
    left = center - len(lines[0]) // 2
    for i, l in enumerate(lines):
        canvas.put(r + i, left, l)
    return r, r + len(lines) - 1, left, left + len(lines[0]) - 1


# ── the map ─────────────────────────────────────────────────────────────────

def build_diagram():
    W = 106
    CTR = 50
    K = [7, 23, 39, 55, 71, 87]          # page card centers, 16 apart
    RAIL = 99                             # the /s/* rail column
    c = Canvas(W)

    # browser
    _, y, _, _ = paint(c, 0, CTR, box_lines(['your browser'], [], single=False, inner=21))
    c.put(y, CTR, '╤')
    c.put(y + 1, CTR, '│  https')
    y += 2

    # dns zone: a bottom port down to the pages hub, a side port out to the /s/* rail
    top, y, zl, zr = paint(c, y, CTR, box_lines(['seaof.glass', 'cloudflare dns zone'], [], single=False))
    c.put(top, CTR, '╧')
    rail_row = top + 2
    c.put(rail_row, zr, '╟')
    c.hline(rail_row, zr + 1, RAIL - 1)
    c.put(rail_row, RAIL, '┐')
    c.put(rail_row, zr + 16, ' /s/* ')
    c.put(y, CTR, '╤')
    c.put(y + 1, CTR - 9, 'GET /*')
    c.put(y + 1, CTR, '│')
    c.put(y + 2, CTR, '│')
    rail_top = rail_row + 1
    y += 3

    # pages hub
    top, y, _, _ = paint(c, y, CTR, box_lines(
        ['github pages · static site', 'repo Lasimeri/lasimeri.github.io'], []))
    c.put(top, CTR, '╧'.replace('╧', '┴'))
    c.put(y, CTR, '┬')

    # fan-out bus to the page cards
    bus = y + 1
    c.hline(bus, K[0], K[-1])
    c.put(bus, K[0], '┌')
    c.put(bus, K[-1], '┐')
    for k in K[1:-1]:
        c.put(bus, k, '┬')
    c.put(bus, CTR, '┴')
    for k in K:
        c.put(bus + 1, k, '│')

    # page cards
    card_top = bus + 2
    fetchers = []
    for k, (path, desc, fetches) in zip(K, CARDS):
        t, b, _, _ = paint(c, card_top, k, box_lines([path, desc], [], inner=13, pad=1))
        c.put(t, k, '┴')
        if fetches:
            fetchers.append(k)
    card_bot = card_top + 3

    # dashed fetch edges from the api-using pages down into the worker
    for k in fetchers:
        c.put(card_bot, k, '┬')
        c.putv(card_bot + 1, card_bot + 2, k, '┆')
    c.put(card_bot + 1, fetchers[0] - 13, 'fetch /s/*')

    # the rail comes down the right margin and elbows into the worker top
    c.putv(rail_top, card_bot + 1, RAIL, '│')
    rail_in = 95
    c.put(card_bot + 2, RAIL, '┘')
    c.hline(card_bot + 2, rail_in + 1, RAIL - 1)
    c.put(card_bot + 2, rail_in, '┌')

    # crystal worker: routes compressed to three families
    wtop = card_bot + 3
    groups = table([(g, routes) for g, routes in WORKER_GROUPS])
    wlines = box_lines(['crystal · cloudflare worker', 'worker/src/index.ts · 60 req/min/ip'],
                       groups, single=False, inner=43)
    wleft = fetchers[0] - 12
    for i, l in enumerate(wlines):
        c.put(wtop + i, wleft, l)
    wbot = wtop + len(wlines) - 1
    wright = wleft + len(wlines[0]) - 1
    for k in fetchers:
        c.put(wtop, k, '╧')
    c.put(wtop, rail_in, '╧')
    assert wleft < fetchers[0] and fetchers[-1] < rail_in < wright, 'worker top ports out of range'

    # client-side annotation in the open left column
    c.put(wtop + 3, 6, 'client-side only:')
    c.put(wtop + 4, 6, '/ittybitty/ · /qii/ · /tools/pgp')
    c.put(wtop + 5, 6, 'never talk to crystal')

    # storage + external services hang off the worker bottom
    r2l = box_lines([R2_BOX[0]], R2_BOX[1], pad=2)
    exl = box_lines([EXT_BOX[0]], EXT_BOX[1], pad=2)
    while len(r2l) < len(exl):
        r2l.insert(-1, '│' + ' ' * (len(r2l[0]) - 2) + '│')
    d1, d2 = 64, 92
    c.put(wbot, d1, '╤')
    c.put(wbot, d2, '╤')
    c.putv(wbot + 1, wbot + 1, d1)
    c.putv(wbot + 1, wbot + 1, d2)
    t1, _, _, _ = paint(c, wbot + 2, d1, r2l)
    t2, _, _, _ = paint(c, wbot + 2, d2, exl)
    c.put(t1, d1, '┴')
    c.put(t2, d2, '┴')

    return c.text()


def table(rows):
    """Align columns; last column of each row absorbs the remainder."""
    ncols = max(len(r) for r in rows)
    widths = [0] * ncols
    for r in rows:
        for i, cell in enumerate(r[:-1]):
            widths[i] = max(widths[i], len(cell) + 3)
    out = []
    for r in rows:
        out.append(''.join(cell.ljust(widths[i]) for i, cell in enumerate(r[:-1])) + r[-1])
    return out


def build_routes():
    body = table([(m, r, d) for m, r, d, _ in ROUTES])
    tagged = [(l, '▸ ' + t if t else '') for l, (_, _, _, t) in zip(body, ROUTES)]
    bw = max(len(l) for l, _ in tagged)
    out = ['crystal routes · https://seaof.glass/s/*', '']
    for l, t in tagged:
        out.append('  ' + (l.ljust(bw + 3) + t if t else l))
    return '\n'.join(out)


def build_flows():
    label_w = max(len(l) for l, _ in FLOWS) + 3
    out = ['the short-link round trip', '']
    for label, s in FLOWS:
        out.append('  ' + label.ljust(label_w) + s)
    out += ['', '', 'client-side only · never talk to crystal', '']
    path_w = max(len(p) for p, _ in CLIENT_ONLY) + 3
    for p, d in CLIENT_ONLY:
        out.append('  ' + p.ljust(path_w) + d)
    return '\n'.join(out)


# ── colorizer ───────────────────────────────────────────────────────────────

def colorize(text):
    out = []
    for line in text.split('\n'):
        l = html.escape(line, quote=False)
        for t in TITLES:
            l = re.sub(r'(?<![-\w·])' + re.escape(t) + r'(?![-\w·])',
                       lambda mm: '<span class="h">' + mm.group(0) + '</span>', l)
        l = re.sub(r'([╔╗╚╝║═╤╧╟╢]+)', r'<span class="d">\1</span>', l)
        l = re.sub(r'([┌┐└┘┬┴│─┼]+)', r'<span class="b">\1</span>', l)
        l = re.sub(r'([┆]+)', r'<span class="a">\1</span>', l)
        l = re.sub(r'([▼▶▸◀])', r'<span class="a">\1</span>', l)
        l = re.sub(r'\b(GET|POST)\b', r'<span class="m">\1</span>', l)
        out.append(l)
    return '\n'.join(out)


# ── page template ───────────────────────────────────────────────────────────

CSS = """\
    :root {
      --bg: #0a0a0f;
      --surface: #12121a;
      --border: #1e1e2e;
      --text: #c4945a;
      --text-dim: #8a6a3e;
      --accent: #c4945a;
      --bright: #e2b273;
      --frame: #453720;
      --frame2: #6b5433;
      --mono: 'SF Mono', 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: var(--mono);
      background: var(--bg);
      background-image: radial-gradient(1100px 500px at 50% -120px, #131320 0%, var(--bg) 65%);
      background-repeat: no-repeat;
      color: var(--text);
      min-height: 100vh;
      display: flex;
      justify-content: center;
      padding: 2rem;
    }
    .container { max-width: 1060px; width: 100%; }
    h1 {
      font-size: 1.1rem;
      font-weight: 400;
      color: var(--accent);
      margin-bottom: 0.5rem;
      letter-spacing: 0.05em;
    }
    h1 a { color: var(--accent); text-decoration: none; }
    h1 a:hover { text-decoration: underline; }
    .subtitle { font-size: 0.7rem; color: var(--text-dim); font-style: italic; opacity: 0.8; margin-bottom: 2rem; }
    .section-label {
      font-size: 0.65rem;
      color: var(--text-dim);
      margin: 2rem 0 0.75rem;
      letter-spacing: 0.1em;
      text-transform: lowercase;
    }
    pre.diagram {
      font-size: 0.68rem;
      line-height: 1.4;
      color: var(--text);
      background: var(--surface);
      background-image: radial-gradient(900px 300px at 50% 0%, rgba(196, 148, 90, 0.035) 0%, transparent 70%);
      border: 1px solid var(--border);
      padding: 1.5rem;
      overflow-x: auto;
    }
    .diagram .b { color: var(--frame); }
    .diagram .d { color: var(--frame2); }
    .diagram .a { color: var(--bright); }
    .diagram .m { color: var(--bright); }
    .diagram .h { color: var(--bright); text-shadow: 0 0 14px rgba(226, 178, 115, 0.25); }
    .roles {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      gap: 1px;
      background: var(--border);
      border: 1px solid var(--border);
    }
    .role {
      background: var(--bg);
      padding: 0.9rem 1.2rem;
      transition: background 0.15s;
    }
    .role:hover { background: var(--surface); }
    .role-name { font-size: 0.75rem; color: var(--accent); margin-bottom: 0.3rem; }
    .role-name span { color: var(--text-dim); }
    .role-desc { font-size: 0.68rem; color: var(--text-dim); line-height: 1.7; }
    .role-desc code { color: var(--text); font-family: var(--mono); }
    .sep { border: none; border-top: 1px solid var(--border); margin: 2rem 0; }
    .footer { font-size: 0.6rem; color: var(--text-dim); opacity: 0.35; line-height: 1.8; }
    .footer a { color: var(--accent); text-decoration: none; }
    .footer a:hover { text-decoration: underline; }
    @media (max-width: 600px) { body { padding: 1.25rem; } }\
"""


def build_page():
    diagram = colorize(build_diagram())
    routes = colorize(build_routes())
    flows = colorize(build_flows())
    roles = '\n'.join(
        f'''      <div class="role">
        <div class="role-name">{name} <span>· {tag}</span></div>
        <div class="role-desc">{desc}</div>
      </div>''' for name, tag, desc in ROLES)

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>sitemap &mdash; sea of glass</title>
  <meta property="og:title" content="sitemap &#8212; sea of glass">
  <meta property="og:description" content="the site, its components, and how they fit together">
  <meta name="theme-color" content="#0a0a0f">
  <style>
{CSS}
  </style>
</head>
<body>
  <div class="container">
    <h1><a href="/">sea of glass</a> / sitemap</h1>
    <p class="subtitle">the site, its components, and how they fit together</p>

    <div class="section-label">&mdash;&mdash; the map &mdash;&mdash;</div>
    <pre class="diagram">
{diagram}
</pre>

    <div class="section-label">&mdash;&mdash; routes &mdash;&mdash;</div>
    <pre class="diagram">
{routes}
</pre>

    <div class="section-label">&mdash;&mdash; flows &mdash;&mdash;</div>
    <pre class="diagram">
{flows}
</pre>

    <div class="section-label">&mdash;&mdash; roles &mdash;&mdash;</div>
    <div class="roles">
{roles}
    </div>

    <hr class="sep">
    <div class="footer">
      &copy; 2025 sea of glass · <a href="/">home</a> · generated by sitemap/build.py
    </div>
  </div>
</body>
</html>
'''


def build_sitemap_xml():
    urls = '\n'.join(
        f'  <url>\n    <loc>https://seaof.glass{p}</loc>\n    <lastmod>{LASTMOD}</lastmod>\n  </url>'
        for p in SITEMAP_XML_PATHS)
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{urls}
</urlset>
'''


if __name__ == '__main__':
    plain = build_diagram()
    assert '\u2014' not in plain, 'em-dash in diagram'
    page = build_page()
    assert '\u2014' not in page, 'em-dash in page'
    with open('sitemap/index.html', 'w') as f:
        f.write(page)
    with open('sitemap.xml', 'w') as f:
        f.write(build_sitemap_xml())
    print(plain)
    print('\nwrote sitemap/index.html and sitemap.xml')
