#!/usr/bin/env python3
# Generates sitemap/index.html and /sitemap.xml from the data model below.
# Edit the model, run `python3 sitemap/build.py` from the repo root, commit both outputs.

import html
import re

# ── data model ──────────────────────────────────────────────────────────────

PAGES = [
    ('/',                'landing page'),
    ('/sitemap/',        'this map, built by build.py'),
    ('/ittybitty/',      'html-in-a-url editor'),
    ('/qii/',            'quake ii via wasm'),
    ('/shrtlnk/',        'shortener ui'),
    ('/shrtlnk/r/',      'redirect splash'),
    ('/tools/',          'ip · headers · dns ·'),
    ('',                 'ping · whois · tmp'),
    ('/tools/pgp.html',  'openpgp, in-browser'),
    ('/tools/pgp/',      'rust→wasm pgp runtime'),
]

ROUTES = [
    ('GET',  '/s/ip',       'your ip, echoed',      ''),
    ('GET',  '/s/headers',  'your request headers', ''),
    ('GET',  '/s/dns/…',    'doh lookup',           'ext'),
    ('GET',  '/s/ping/…',   'timed fetch',          'ext'),
    ('GET',  '/s/whois/…',  'rdap lookup',          'ext'),
    ('POST', '/s/go',       'mint short link',      'r2'),
    ('GET',  '/s/go/:id',   'resolve link',         'r2'),
    ('POST', '/s/tmp',      'file drop, 1 hr',      'r2'),
    ('GET',  '/s/tmp/:id',  'fetch file',           'r2'),
]

R2_BOX = ('r2 · sea-glass-store', [
    'short:* → target urls',
    'tmp:*   → files, 1 hr',
])

EXT_BOX = ('external services', [
    'cloudflare-dns.com',
    'rdap.org / verisign',
    'any pinged target',
])

FLOWS = [
    ('mint',    '/shrtlnk/ ── POST /s/go ──▶ crystal ── put short:id ──▶ r2'),
    ('reply',   'crystal ──▶ { id, https://seaof.glass/s/go/id }'),
    ('resolve', 'visitor ── GET /s/go/id ──▶ crystal ── get short:id ──▶ r2'),
    ('land',    'crystal ── 302 ──▶ /shrtlnk/r/?to=target ── click-through ──▶ target'),
]

CLIENT_ONLY = [
    ('/ittybitty/', 'the document lives in the url fragment'),
    ('/qii/',       'game data cached in indexeddb'),
    ('/tools/pgp',  'keys and plaintext never leave the tab'),
]

TITLES = [
    'your browser',
    'seaof.glass',
    'cloudflare dns zone',
    'github pages · static site',
    'crystal · cloudflare worker',
    'r2 · sea-glass-store',
    'external services',
    'the short-link round trip',
    'client-side only · never talk to crystal',
]

ROLES = [
    ('/', 'landing',
     'the front door. one hand-written page, inline css, zero javascript. '
     'links to everything below and nothing else.'),
    ('/sitemap/', 'this page',
     'the map you are reading, generated by <code>sitemap/build.py</code>: '
     'edit the data model, run it, commit the output. the diagram geometry is '
     'computed, never hand-aligned.'),
    ('/ittybitty/', 'the url is the document',
     'an editor whose files live entirely in the link: content is lzma-compressed '
     '(and optionally encrypted) into the url fragment, so sharing the link '
     '<em>is</em> publishing. codemirror for editing, marked for markdown preview, '
     'qr export for handing a whole document to a phone, and a service worker that '
     'makes it installable and offline-capable. no server ever sees a byte of the '
     'document, because the fragment never leaves the browser.'),
    ('/qii/', 'quake ii',
     'the qwasm2 engine compiled to webassembly, with gl1, gles3, and software '
     'renderers. jszip unpacks game data in the browser and indexeddb '
     '(<code>qii-assets</code>) caches the pak files, so the download happens once. '
     'after the first load it is a local game that happens to live at a url.'),
    ('/shrtlnk/', 'url shortener',
     'the ui posts a url to <code>/s/go</code> and gets back '
     '<code>seaof.glass/s/go/:id</code>. resolving a short link never jumps straight '
     'to the target: crystal 302s to the <code>/shrtlnk/r/</code> splash, which '
     'previews the destination behind a disclaimer and a deliberate click-through. '
     'no blind redirects.'),
    ('/tools/', 'seven single-file utilities',
     '<code>ip</code>, <code>headers</code>, <code>dns</code>, <code>ping</code>, and '
     '<code>whois</code> are thin fronts for the matching <code>/s/*</code> route: '
     'the worker either reflects what it sees (your ip, your headers) or asks the '
     'outside world on your behalf (doh, rdap, a timed fetch). <code>tmp</code> '
     'drops a file into r2 with a one-hour expiry. <code>pgp</code> is the odd one '
     'out: it needs no server at all.'),
    ('/tools/pgp/', 'openpgp runtime',
     'rust (the rPGP crate) compiled to wasm, executed inside a web worker so '
     'rsa-4096 keygen does not freeze the tab. keygen, encrypt, and decrypt all run '
     'locally; keys and plaintext never leave the page. the rust source ships '
     'alongside the built wasm, so the artifact is reproducible.'),
    ('crystal', 'cloudflare worker',
     'the only server code on the site: one typescript file behind '
     '<code>seaof.glass/s/*</code>. nine routes, rate-limited to 60 requests a '
     'minute per ip, cors locked to the site origin. it holds no logic beyond what '
     'the static pages cannot do themselves: reflecting network facts, fetching '
     'cross-origin, and touching storage.'),
    ('r2', 'sea-glass-store',
     'the only state anywhere. <code>short:*</code> keys map ids to target urls and '
     'live forever; <code>tmp:*</code> keys hold uploads stamped with an expiry that '
     'is checked, and purged, on read. everything else on the site is stateless or '
     'client-side.'),
    ('the repo', 'Lasimeri/lasimeri.github.io',
     'both halves live in one repository. a push to <code>main</code> republishes '
     'the static site through github pages; <code>wrangler deploy</code> in '
     '<code>worker/</code> republishes crystal. the two deploys are independent and '
     'meet only at the <code>/s/*</code> fetch boundary.'),
]

SITEMAP_XML_PATHS = [
    '/', '/sitemap/', '/ittybitty/', '/qii/', '/shrtlnk/',
    '/tools/ip.html', '/tools/headers.html', '/tools/dns.html',
    '/tools/ping.html', '/tools/whois.html', '/tools/tmp.html',
    '/tools/pgp.html',
]
LASTMOD = '2026-08-13'

# ── layout engine ───────────────────────────────────────────────────────────

PAD = 3          # spaces inside each box edge
GAP = 9          # gap between the two main boxes; odd so the canvas has an exact center column
SUBGAP = 3       # gap between the two bottom boxes


def table(rows):
    """Align columns; last column of each row absorbs the remainder."""
    ncols = max(len(r) for r in rows)
    widths = [0] * ncols
    for r in rows:
        for i, cell in enumerate(r[:-1]):
            widths[i] = max(widths[i], len(cell) + 2)
    out = []
    for r in rows:
        line = ''.join(cell.ljust(widths[i]) for i, cell in enumerate(r[:-1])) + r[-1]
        out.append(line)
    return out


def box(titles, body, inner=None, odd=False):
    """Return list of border-to-border lines. Titles centered, body left at PAD.
    odd=True forces an odd outer width so the box has an exact center column."""
    content = list(titles) + ([''] if body else []) + list(body)
    need = max(len(l) for l in content) + 2 * PAD
    w = max(need, inner or 0)
    if odd and (w + 2) % 2 == 0:
        w += 1
    lines = ['┌' + '─' * w + '┐']
    for i, l in enumerate(content):
        if i < len(titles):
            lines.append('│' + l.center(w) + '│')
        else:
            lines.append('│' + (' ' * PAD + l).ljust(w) + '│')
    lines.append('└' + '─' * w + '┘')
    return lines


def equalize(a, b):
    """Pad the shorter box with blank rows above its bottom border."""
    while len(a) < len(b):
        a.insert(-1, '│' + ' ' * (len(a[0]) - 2) + '│')
    while len(b) < len(a):
        b.insert(-1, '│' + ' ' * (len(b[0]) - 2) + '│')


def put(row, col, s):
    """Overlay string s onto row (a list of chars) at col."""
    row[col:col + len(s)] = list(s)


def build_diagram():
    # main boxes, forced to equal width and height
    left_body = table([(p, d) for p, d in PAGES])
    right_body = table([(m, r, d) for m, r, d, _ in ROUTES])
    tagged = []
    for line, (_, _, _, tag) in zip(right_body, ROUTES):
        tagged.append((line, '▸ ' + tag if tag else ''))
    body_w = max(len(l) for l, _ in tagged)
    right_body = [(l.ljust(body_w + 2) + t) if t else l for l, t in tagged]

    L_TITLES = ['github pages · static site', 'repo Lasimeri/lasimeri.github.io']
    R_TITLES = ['crystal · cloudflare worker', 'worker/src/index.ts · 60 req/min/ip']
    W = max(len(box(L_TITLES, left_body)[0]), len(box(R_TITLES, right_body)[0]))
    W += (W % 2 == 0)          # odd width: each main box has an exact center column
    lbox = box(L_TITLES, left_body, inner=W - 2)
    rbox = box(R_TITLES, right_body, inner=W - 2)
    equalize(lbox, rbox)

    TOTAL = 2 * W + GAP        # odd + odd + odd GAP keeps TOTAL odd: exact canvas center
    CL = W // 2
    CR = TOTAL - 1 - CL        # mirror of CL: elbows come out perfectly symmetric

    lines = []

    # tier 1: browser, centered; stem column derived from its placement
    bro = box(['your browser'], [], inner=23, odd=True)
    bpad = (TOTAL - len(bro[0])) // 2
    stem = bpad + len(bro[0]) // 2
    lines.append(' ' * bpad + bro[0])
    lines.append(' ' * bpad + bro[1])
    bot = list(' ' * bpad + bro[2])
    bot[stem] = '┬'
    lines.append(''.join(bot))
    lines.append(' ' * stem + '│  https')

    # tier 2: dns zone, centered, ┴ aligned to the browser stem
    zone = box(['seaof.glass', 'cloudflare dns zone'], [], inner=27, odd=True)
    zpad = (TOTAL - len(zone[0])) // 2
    zw = len(zone[0])
    top = list(' ' * zpad + zone[0])
    top[stem] = '┴'
    lines.append(''.join(top))
    for l in zone[1:-1]:
        lines.append(' ' * zpad + l)
    m = zw // 4                       # symmetric drop points on the bottom border
    c1 = zpad + m
    c2 = TOTAL - 1 - c1               # mirror of c1 across the canvas center
    zbot = list(' ' * zpad + zone[-1])
    zbot[c1] = '┬'
    zbot[c2] = '┬'
    lines.append(''.join(zbot))

    # labeled stems, then elbows out to each main box center
    assert stem == TOTAL // 2, 'browser stem must sit on the canvas center'
    assert c1 - CL == CR - c2, 'elbow runs must be mirror-symmetric'

    row = [' '] * TOTAL
    lab_l, lab_r = 'static GET /* ', ' api GET|POST /s/*'
    put(row, c1 - len(lab_l), lab_l)
    row[c1] = '│'
    row[c2] = '│'
    put(row, c2 + 1, lab_r)
    lines.append(''.join(row).rstrip())

    row = [' '] * TOTAL
    row[CL] = '┌'
    for i in range(CL + 1, c1):
        row[i] = '─'
    row[c1] = '┘'
    row[c2] = '└'
    for i in range(c2 + 1, CR):
        row[i] = '─'
    row[CR] = '┐'
    lines.append(''.join(row).rstrip())
    for ch in ('│', '▼'):
        row = [' '] * TOTAL
        row[CL] = ch
        row[CR] = ch
        lines.append(''.join(row).rstrip())

    # tier 3: the two main boxes; r2/ext stems drop from the worker box border
    r2box = box([R2_BOX[0]], R2_BOX[1], odd=True)
    exbox = box([EXT_BOX[0]], EXT_BOX[1], odd=True)
    equalize(r2box, exbox)
    sub_w = len(r2box[0]) + SUBGAP + len(exbox[0])
    sub_start = W + GAP + (W - sub_w) // 2
    d1 = sub_start + len(r2box[0]) // 2
    d2 = sub_start + len(r2box[0]) + SUBGAP + len(exbox[0]) // 2
    assert W + GAP < d1 < d2 < TOTAL - 1, 'stems must fall inside the worker box'

    for i in range(len(lbox)):
        l, r = lbox[i], rbox[i]
        if i == len(lbox) - 1:
            r = list(r)
            r[d1 - (W + GAP)] = '┬'
            r[d2 - (W + GAP)] = '┬'
            r = ''.join(r)
        lines.append(l + ' ' * GAP + r)

    for ch in ('│', '▼'):
        row = [' '] * TOTAL
        row[d1] = ch
        row[d2] = ch
        lines.append(''.join(row).rstrip())

    # tier 4: storage and external boxes, centered under their stems
    for i in range(len(r2box)):
        row = [' '] * TOTAL
        put(row, sub_start, r2box[i])
        put(row, sub_start + len(r2box[0]) + SUBGAP, exbox[i])
        lines.append(''.join(row).rstrip())

    return '\n'.join(l.rstrip() for l in lines)


def build_flows():
    label_w = max(len(l) for l, _ in FLOWS) + 3
    out = ['the short-link round trip', '']
    for label, s in FLOWS:
        out.append('  ' + label.ljust(label_w) + s)
    out += ['', '', 'client-side only · never talk to crystal', '']
    path_w = max(len(p) for p, _ in CLIENT_ONLY) + 3
    for p, d in CLIENT_ONLY:
        out.append('  ' + p.ljust(path_w) + d)
    return '\n'.join(out)


# ── colorizer ───────────────────────────────────────────────────────────────

def colorize(text):
    out = []
    for line in text.split('\n'):
        l = html.escape(line, quote=False)
        for t in TITLES:
            l = re.sub(r'(?<![\w·])' + re.escape(t) + r'(?![\w·])',
                       lambda mm: '<span class="h">' + mm.group(0) + '</span>', l)
        l = re.sub(r'([┌┐└┘┬┴│─]+)', r'<span class="b">\1</span>', l)
        l = re.sub(r'([▼▶▸])', r'<span class="a">\1</span>', l)
        l = re.sub(r'\b(GET|POST)\b', r'<span class="m">\1</span>', l)
        out.append(l)
    return '\n'.join(out)


# ── page template ───────────────────────────────────────────────────────────

CSS = """\
    :root {
      --bg: #0a0a0f;
      --surface: #12121a;
      --border: #1e1e2e;
      --text: #c4945a;
      --text-dim: #8a6a3e;
      --accent: #c4945a;
      --bright: #e2b273;
      --frame: #4a3b25;
      --mono: 'SF Mono', 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: var(--mono);
      background: var(--bg);
      background-image: radial-gradient(1100px 500px at 50% -120px, #131320 0%, var(--bg) 65%);
      background-repeat: no-repeat;
      color: var(--text);
      min-height: 100vh;
      display: flex;
      justify-content: center;
      padding: 2rem;
    }
    .container { max-width: 1060px; width: 100%; }
    h1 {
      font-size: 1.1rem;
      font-weight: 400;
      color: var(--accent);
      margin-bottom: 0.5rem;
      letter-spacing: 0.05em;
    }
    h1 a { color: var(--accent); text-decoration: none; }
    h1 a:hover { text-decoration: underline; }
    .subtitle { font-size: 0.7rem; color: var(--text-dim); font-style: italic; opacity: 0.8; margin-bottom: 2rem; }
    .section-label {
      font-size: 0.65rem;
      color: var(--text-dim);
      margin: 2rem 0 0.75rem;
      letter-spacing: 0.1em;
      text-transform: lowercase;
    }
    pre.diagram {
      font-size: 0.68rem;
      line-height: 1.4;
      color: var(--text);
      background: var(--surface);
      background-image: radial-gradient(900px 300px at 50% 0%, rgba(196, 148, 90, 0.035) 0%, transparent 70%);
      border: 1px solid var(--border);
      padding: 1.5rem;
      overflow-x: auto;
    }
    .diagram .b { color: var(--frame); }
    .diagram .a { color: var(--bright); }
    .diagram .m { color: var(--bright); }
    .diagram .h { color: var(--bright); text-shadow: 0 0 14px rgba(226, 178, 115, 0.25); }
    .roles {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
      gap: 1px;
      background: var(--border);
      border: 1px solid var(--border);
    }
    .role {
      background: var(--bg);
      padding: 0.9rem 1.2rem;
      transition: background 0.15s;
    }
    .role:hover { background: var(--surface); }
    .role-name { font-size: 0.75rem; color: var(--accent); margin-bottom: 0.3rem; }
    .role-name span { color: var(--text-dim); }
    .role-desc { font-size: 0.68rem; color: var(--text-dim); line-height: 1.7; }
    .role-desc code { color: var(--text); font-family: var(--mono); }
    .sep { border: none; border-top: 1px solid var(--border); margin: 2rem 0; }
    .footer { font-size: 0.6rem; color: var(--text-dim); opacity: 0.35; line-height: 1.8; }
    .footer a { color: var(--accent); text-decoration: none; }
    .footer a:hover { text-decoration: underline; }
    @media (max-width: 600px) { body { padding: 1.25rem; } }\
"""


def build_page():
    diagram = colorize(build_diagram())
    flows = colorize(build_flows())
    roles = '\n'.join(
        f'''      <div class="role">
        <div class="role-name">{name} <span>· {tag}</span></div>
        <div class="role-desc">{desc}</div>
      </div>''' for name, tag, desc in ROLES)

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>sitemap &mdash; sea of glass</title>
  <meta property="og:title" content="sitemap &#8212; sea of glass">
  <meta property="og:description" content="the site, its components, and how they fit together">
  <meta name="theme-color" content="#0a0a0f">
  <style>
{CSS}
  </style>
</head>
<body>
  <div class="container">
    <h1><a href="/">sea of glass</a> / sitemap</h1>
    <p class="subtitle">the site, its components, and how they fit together</p>

    <div class="section-label">&mdash;&mdash; the map &mdash;&mdash;</div>
    <pre class="diagram">
{diagram}
</pre>

    <div class="section-label">&mdash;&mdash; flows &mdash;&mdash;</div>
    <pre class="diagram">
{flows}
</pre>

    <div class="section-label">&mdash;&mdash; roles &mdash;&mdash;</div>
    <div class="roles">
{roles}
    </div>

    <hr class="sep">
    <div class="footer">
      &copy; 2025 sea of glass · <a href="/">home</a> · generated by sitemap/build.py
    </div>
  </div>
</body>
</html>
'''


def build_sitemap_xml():
    urls = '\n'.join(
        f'  <url>\n    <loc>https://seaof.glass{p}</loc>\n    <lastmod>{LASTMOD}</lastmod>\n  </url>'
        for p in SITEMAP_XML_PATHS)
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{urls}
</urlset>
'''


# ── checks + write ──────────────────────────────────────────────────────────

def verify(diagram_text):
    lines = diagram_text.split('\n')
    for l in lines:
        for a, b in (('┌', '┐'), ('└', '┘')):
            if a in l:
                assert l.count(a) == l.count(b), f'unbalanced corners: {l!r}'
    assert '\u2014' not in diagram_text, 'em-dash in diagram'


if __name__ == '__main__':
    plain = build_diagram()
    verify(plain)
    page = build_page()
    assert '\u2014' not in page, 'em-dash in page'
    with open('sitemap/index.html', 'w') as f:
        f.write(page)
    with open('sitemap.xml', 'w') as f:
        f.write(build_sitemap_xml())
    print(plain)
    print('\nwrote sitemap/index.html and sitemap.xml')
