#!/usr/bin/env python3
# Generates sitemap/index.html and /sitemap.xml from the data model below.
# Edit the model, run `python3 sitemap/build.py` from the repo root, commit both outputs.
#
# The page is an ASCII tree of native <details> dropdowns: branch glyphs are
# computed here, explanations expand in place, and the page ships zero javascript.

import html
import re

# ── data model: (label, hint, description-html, children) ───────────────────

TREE = [
    ('github pages', 'the static half', (
        'github pages serves this repo at seaof.glass (via CNAME). a push to '
        '<code>main</code> republishes the whole site; <code>.nojekyll</code> keeps '
        'the files verbatim. everything under this node is plain files: no build '
        'step, no server, no javascript unless a page brings its own.'), [

        ('/', 'landing page', (
            'the front door. one hand-written page, inline css, zero javascript. '
            'links to everything on the site and nothing else.'), []),

        ('/sitemap/', 'this page', (
            'the map you are reading, generated by <code>sitemap/build.py</code>: '
            'edit the data model, run it, commit the output. the dropdowns are native '
            'html <code>&lt;details&gt;</code> elements, so the page is still zero '
            'javascript.'), []),

        ('/ittybitty/', 'the url is the document', (
            'an editor whose files live entirely in the link: content is '
            'lzma-compressed (and optionally encrypted) into the url fragment, so '
            'sharing the link <em>is</em> publishing. codemirror for editing, marked '
            'for markdown preview, qr export for handing a document to a phone, and '
            'a service worker that makes it installable and offline-capable. no '
            'server ever sees a byte of the document: the fragment never leaves the '
            'browser.'), []),

        ('/qii/', 'quake ii', (
            'the qwasm2 engine compiled to webassembly, with gl1, gles3, and '
            'software renderers. jszip unpacks game data in the browser and '
            'indexeddb (<code>qii-assets</code>) caches the pak files, so the '
            'download happens once. after the first load it is a local game that '
            'happens to live at a url.'), []),

        ('/shrtlnk/', 'url shortener', (
            'the ui posts a url to <code>/s/go</code> and gets back '
            '<code>seaof.glass/s/go/:id</code>. resolving a short link never jumps '
            'straight to the target: crystal 302s to the splash below, which '
            'previews the destination and waits for a deliberate click. no blind '
            'redirects.'), [

            ('/shrtlnk/r/', 'redirect splash', (
                'the click-through page every short link lands on: shows the target '
                'url behind a disclaimer, sends no referrer, and is marked noindex. '
                'the deliberate click is the only way forward.'), []),
        ]),

        ('/tools/', 'seven single-file utilities', (
            'each tool is one html file. five of them are thin fronts for a '
            'matching <code>/s/*</code> route on crystal; <code>tmp</code> stores '
            'through crystal into r2; <code>pgp</code> needs no server at all.'), [

            ('ip.html', 'what is my ip', (
                'asks <code>GET /s/ip</code>; crystal echoes the connecting ip '
                '(the <code>CF-Connecting-IP</code> header) back as plain text.'), []),

            ('headers.html', 'request inspector', (
                'asks <code>GET /s/headers</code>; crystal reflects every request '
                'header back as json, so you see exactly what a server sees.'), []),

            ('dns.html', 'dns lookup', (
                'queries <code>GET /s/dns/:type/:domain</code>; crystal relays to '
                'cloudflare doh. allowed types: A, AAAA, MX, TXT, CNAME, NS, '
                'SOA.'), []),

            ('ping.html', 'http ping', (
                'calls <code>GET /s/ping/:url</code>; crystal fetches the target '
                'with a 5 second abort and reports status, latency in ms, and '
                'response headers.'), []),

            ('whois.html', 'rdap lookup', (
                'calls <code>GET /s/whois/:domain</code>; rdap via rdap.org with a '
                'verisign fallback for .com and .net.'), []),

            ('tmp.html', 'temp file drop', (
                'uploads up to 10 mb via <code>POST /s/tmp</code> into r2. links '
                'live one hour; expired objects are purged the next time they are '
                'read.'), []),

            ('pgp.html', 'openpgp, in-browser', (
                'keygen, encrypt, and decrypt with no server involvement at all. '
                'the crypto runs in the wasm runtime below.'), [

                ('/tools/pgp/', 'rust→wasm runtime', (
                    'rust (the rPGP crate) compiled to wasm, executed inside a web '
                    'worker so rsa-4096 keygen does not freeze the tab. keys and '
                    'plaintext never leave the page. the rust source ships alongside '
                    'the built wasm, so the artifact is reproducible.'), []),
            ]),
        ]),
    ]),

    ('crystal', 'cloudflare worker · /s/*', (
        'the only server code on the site: one typescript file '
        '(<code>worker/src/index.ts</code>) behind <code>seaof.glass/s/*</code>. '
        'rate-limited to 60 requests a minute per ip, cors locked to the site '
        'origin (plus localhost for dev). deployed with <code>wrangler deploy</code>, '
        'independent of the pages deploy. it holds no logic beyond what static '
        'pages cannot do themselves: reflecting network facts, fetching '
        'cross-origin, and touching storage.'), [

        ('GET /s/ip', 'reflect', (
            'returns the caller\'s ip as plain text.'), []),

        ('GET /s/headers', 'reflect', (
            'returns the caller\'s request headers as json.'), []),

        ('GET /s/dns/:type/:domain', 'lookup', (
            'doh relay to cloudflare-dns.com. allowed types: A, AAAA, MX, TXT, '
            'CNAME, NS, SOA.'), []),

        ('GET /s/ping/:url', 'lookup', (
            'timed fetch of the target with a 5 second abort; reports status, '
            'milliseconds, and response headers.'), []),

        ('GET /s/whois/:domain', 'lookup', (
            'rdap lookup via rdap.org, falling back to verisign for .com and '
            '.net.'), []),

        ('POST /s/go', 'store', (
            'mints a random 6-hex-char id and stores <code>short:id → url</code> '
            'in r2.'), []),

        ('GET /s/go/:id', 'store', (
            'resolves the id from r2 and 302s to the <code>/shrtlnk/r/</code> '
            'splash; never a blind redirect.'), []),

        ('POST /s/tmp', 'store', (
            'accepts up to 10 mb and stores it in r2 stamped with a one-hour '
            'expiry.'), []),

        ('GET /s/tmp/:id', 'store', (
            'serves the stored file; expired entries answer 410 and are deleted '
            'on read.'), []),
    ]),

    ('r2 · sea-glass-store', 'the only state', (
        'everything else on the site is stateless or client-side; this bucket is '
        'the single place data rests. <code>short:*</code> keys map ids to target '
        'urls and live forever; <code>tmp:*</code> keys hold uploads stamped with '
        'an expiry that is checked, and purged, on read.'), []),

    ('external services', 'what crystal talks to', (
        'the outside world, reached only server-side by crystal on your behalf: '
        'cloudflare-dns.com for doh lookups, rdap.org and verisign for whois, and '
        'whatever target you point ping at. the browser never contacts these '
        'directly.'), []),

    ('the repo', 'Lasimeri/lasimeri.github.io', (
        'both halves live in one repository. a push to <code>main</code> '
        'republishes the static site through github pages; <code>wrangler '
        'deploy</code> in <code>worker/</code> republishes crystal. the two deploys '
        'are independent and meet only at the <code>/s/*</code> fetch '
        'boundary.'), []),
]

SITEMAP_XML_PATHS = [
    '/', '/sitemap/', '/ittybitty/', '/qii/', '/shrtlnk/',
    '/tools/ip.html', '/tools/headers.html', '/tools/dns.html',
    '/tools/ping.html', '/tools/whois.html', '/tools/tmp.html',
    '/tools/pgp.html',
]
LASTMOD = '2026-08-13'

# ── tree renderer ───────────────────────────────────────────────────────────

def render_nodes(nodes, ancestors):
    """Render sibling nodes; ancestors is a list of is-last flags above us."""
    pad = max(len(label) for label, _, _, _ in nodes)
    out = []
    for i, (label, hint, desc, children) in enumerate(nodes):
        last = i == len(nodes) - 1
        prefix = ''.join('    ' if a else '│   ' for a in ancestors) + \
                 ('└── ' if last else '├── ')
        lbl = html.escape(label.ljust(pad), quote=False)
        lbl = re.sub(r'^(GET|POST)\b', r'<span class="m">\1</span>', lbl)
        indent = len(prefix) + 2
        out.append(
            f'<details>'
            f'<summary><span class="b">{prefix}</span><span class="caret"></span>'
            f'<span class="lbl">{lbl}</span>'
            f'  <span class="hint">{html.escape(hint, quote=False)}</span></summary>'
            f'<div class="nd" style="margin-left: {indent}ch">{desc}</div>')
        if children:
            out.append(render_nodes(children, ancestors + [last]))
        out.append('</details>')
    return '\n'.join(out)


def build_tree():
    return (
        '<div class="root"><span class="h">seaof.glass</span>'
        ' <span class="hint">· click a node to expand it</span></div>\n'
        + render_nodes(TREE, [])
    )


# ── page template ───────────────────────────────────────────────────────────

CSS = """\
    :root {
      --bg: #0a0a0f;
      --surface: #12121a;
      --border: #1e1e2e;
      --text: #c4945a;
      --text-dim: #8a6a3e;
      --accent: #c4945a;
      --bright: #e2b273;
      --frame: #453720;
      --frame2: #6b5433;
      --mono: 'SF Mono', 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: var(--mono);
      background: var(--bg);
      background-image: radial-gradient(1100px 500px at 50% -120px, #131320 0%, var(--bg) 65%);
      background-repeat: no-repeat;
      color: var(--text);
      min-height: 100vh;
      display: flex;
      justify-content: center;
      padding: 2rem;
    }
    .container { max-width: 900px; width: 100%; }
    h1 {
      font-size: 1.1rem;
      font-weight: 400;
      color: var(--accent);
      margin-bottom: 0.5rem;
      letter-spacing: 0.05em;
    }
    h1 a { color: var(--accent); text-decoration: none; }
    h1 a:hover { text-decoration: underline; }
    .subtitle { font-size: 0.7rem; color: var(--text-dim); font-style: italic; opacity: 0.8; margin-bottom: 2rem; }
    .section-label {
      font-size: 0.65rem;
      color: var(--text-dim);
      margin: 2rem 0 0.75rem;
      letter-spacing: 0.1em;
      text-transform: lowercase;
    }
    .tree {
      font-size: 0.72rem;
      line-height: 1.7;
      background: var(--surface);
      background-image: radial-gradient(900px 300px at 50% 0%, rgba(196, 148, 90, 0.035) 0%, transparent 70%);
      border: 1px solid var(--border);
      padding: 1.25rem 1.5rem;
      overflow-x: auto;
    }
    .tree .root {
      white-space: pre;
      margin-bottom: 0.35rem;
    }
    .tree .h { color: var(--bright); text-shadow: 0 0 14px rgba(226, 178, 115, 0.25); }
    .tree summary {
      list-style: none;
      cursor: pointer;
      white-space: pre;
    }
    .tree summary::-webkit-details-marker { display: none; }
    .tree summary .caret::before { content: '▸ '; color: var(--bright); }
    .tree details[open] > summary .caret::before { content: '▾ '; }
    .tree summary:hover .lbl { color: var(--bright); }
    .tree .b { color: var(--frame2); }
    .tree .m { color: var(--bright); }
    .tree .lbl { color: var(--text); }
    .tree .hint { color: var(--text-dim); }
    .tree .nd {
      white-space: normal;
      color: var(--text-dim);
      line-height: 1.7;
      max-width: 60ch;
      border-left: 1px solid var(--border);
      padding: 0.3rem 0 0.3rem 1rem;
      margin-top: 0.25rem;
      margin-bottom: 0.5rem;
    }
    .tree .nd code, .tree .nd em { color: var(--text); font-style: normal; }
    .sep { border: none; border-top: 1px solid var(--border); margin: 2rem 0; }
    .footer { font-size: 0.6rem; color: var(--text-dim); opacity: 0.35; line-height: 1.8; }
    .footer a { color: var(--accent); text-decoration: none; }
    .footer a:hover { text-decoration: underline; }
    @media (max-width: 600px) { body { padding: 1.25rem; } }\
"""


def build_page():
    tree = build_tree()
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>sitemap &mdash; sea of glass</title>
  <meta property="og:title" content="sitemap &#8212; sea of glass">
  <meta property="og:description" content="the site, its components, and how they fit together">
  <meta name="theme-color" content="#0a0a0f">
  <style>
{CSS}
  </style>
</head>
<body>
  <div class="container">
    <h1><a href="/">sea of glass</a> / sitemap</h1>
    <p class="subtitle">the site, its components, and how they fit together</p>

    <div class="section-label">&mdash;&mdash; the map &mdash;&mdash;</div>
    <div class="tree">
{tree}
    </div>

    <hr class="sep">
    <div class="footer">
      &copy; 2025 sea of glass · <a href="/">home</a> · generated by sitemap/build.py
    </div>
  </div>
</body>
</html>
'''


def build_sitemap_xml():
    urls = '\n'.join(
        f'  <url>\n    <loc>https://seaof.glass{p}</loc>\n    <lastmod>{LASTMOD}</lastmod>\n  </url>'
        for p in SITEMAP_XML_PATHS)
    return f'''<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{urls}
</urlset>
'''


if __name__ == '__main__':
    page = build_page()
    assert '\u2014' not in page, 'em-dash in page'
    with open('sitemap/index.html', 'w') as f:
        f.write(page)
    with open('sitemap.xml', 'w') as f:
        f.write(build_sitemap_xml())
    n = page.count('<details>')
    assert n == page.count('</details>'), 'unbalanced details'
    print(f'wrote sitemap/index.html ({n} dropdown nodes) and sitemap.xml')
