name = "crystal"
main = "src/index.ts"
compatibility_date = "2026-04-07"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = false

[[r2_buckets]]
binding = "STORE"
bucket_name = "sea-glass-store"

[[routes]]
pattern = "seaof.glass/s/*"
zone_name = "seaof.glass"
